name: Release and publish

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release on tags, attach asset on release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: Install dependencies and build
        run: |
          python -m pip install --upgrade pip
          pip install twine build
          python -m build
      - name: Upload to Pypi
        if: startsWith(github.ref, 'refs/tags/')
        run: twine upload -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" dist/cosmian_anonymization*.whl
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
